# Copyright (C) 2019 Intel Corporation 
# SPDX-License-Identifier: BSD-3-Clause 
 
version: "3.4" 

services:
  portainer_edge_agent:
    image: portainer/agent:1.6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data
    environment:
     - AGENT_CLUSTER_ADDR=tasks.portainer_edge_agent
     - CAP_HOST_MANAGEMENT=1
     - EDGE=${EDGE}
     - EDGE_ID=${EDGE_ID}
     - EDGE_KEY=${EDGE_KEY}
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  agent_network:
    driver: overlay
    attachable: true
    
volumes:
    portainer_agent_data:
